// Auto-generated by scripts/sync-all.mjs — do not edit manually.
// Source: /home/arthur/dev/skills

export type SkillCategory = "ai" | "c" | "cuda" | "frontend" | "go" | "rust" | "shaders" | "tools";

export interface Skill {
  name: string;
  title: string;
  description: string;
  category: SkillCategory;
  references: number;
}

export const categoryMeta: Record<
  SkillCategory,
  { label: string; color: string; borderColor: string }
> = {
  rust: { label: "Rust", color: "text-orange-600 dark:text-orange-400 bg-orange-500/10", borderColor: "border-t-orange-500" },
  c: { label: "C", color: "text-red-600 dark:text-red-400 bg-red-500/10", borderColor: "border-t-red-500" },
  go: { label: "Go", color: "text-cyan-600 dark:text-cyan-400 bg-cyan-500/10", borderColor: "border-t-cyan-500" },
  frontend: { label: "Frontend & Web", color: "text-blue-600 dark:text-blue-400 bg-blue-500/10", borderColor: "border-t-blue-500" },
  shaders: { label: "3D Graphics & Shaders", color: "text-violet-600 dark:text-violet-400 bg-violet-500/10", borderColor: "border-t-violet-500" },
  cuda: { label: "GPU / CUDA", color: "text-lime-600 dark:text-lime-400 bg-lime-500/10", borderColor: "border-t-lime-500" },
  ai: { label: "AI & Data", color: "text-emerald-600 dark:text-emerald-400 bg-emerald-500/10", borderColor: "border-t-emerald-500" },
  tools: { label: "Tools & Workflows", color: "text-neutral-600 dark:text-neutral-400 bg-neutral-500/10", borderColor: "border-t-neutral-500" },
};

export const skills: Skill[] = [
  {
    "name": "agent-swarm",
    "title": "Agent Swarm",
    "description": "Best practices for orchestrating Claude Code agent teams (swarm mode). Use when: (1) the user asks to create an agent team, swarm, or multi-agent setup, (2) spawning teammates for parallel work, (3)...",
    "category": "tools",
    "references": 3
  },
  {
    "name": "angular-best-practices",
    "title": "Angular Best Practices",
    "description": "Angular v20+ best practices - standalone components, signals, dependency injection, routing, reactive forms, HttpClient, control flow, defer blocks, SSR, hydration, zoneless, OnPush. Use when...",
    "category": "frontend",
    "references": 8
  },
  {
    "name": "async-stripe",
    "title": "Async Stripe",
    "description": "Development guide for the async-stripe Rust crate: strongly-typed async Stripe API bindings generated from OpenAPI spec. Use when working in the async-stripe repository for: (1) Modifying the code...",
    "category": "rust",
    "references": 2
  },
  {
    "name": "c-best-practices",
    "title": "C Best Practices",
    "description": "C programming best practices, idiomatic patterns, and safe coding for modern C (C11/C17/C23). Covers memory management (malloc/calloc/realloc/free, leak prevention), pointer safety, undefined...",
    "category": "c",
    "references": 5
  },
  {
    "name": "caustics-r3f",
    "title": "Caustics R3f",
    "description": ">-",
    "category": "shaders",
    "references": 2
  },
  {
    "name": "clerk-best-practices",
    "title": "Clerk Best Practices",
    "description": ">-",
    "category": "frontend",
    "references": 10
  },
  {
    "name": "clerk-rs-sdk",
    "title": "Clerk Rs Sdk",
    "description": "clerk-rs Rust SDK for Clerk authentication: client setup, typed API calls, JWT validation, and framework middleware (Axum, Actix, Rocket, Poem). Use when writing, reviewing, or refactoring Rust code...",
    "category": "rust",
    "references": 1
  },
  {
    "name": "coss-ui",
    "title": "Coss Ui",
    "description": "coss ui component library built on Base UI and Tailwind CSS for React applications. Copy-paste ownership model with 50+ accessible, composable components. Use when: (1) Building React UI with coss ui...",
    "category": "frontend",
    "references": 5
  },
  {
    "name": "cuda-best-practices",
    "title": "Cuda Best Practices",
    "description": "NVIDIA CUDA C/C++ GPU programming best practices and performance optimization. Covers kernel design, thread/block/grid hierarchy, memory hierarchy (global, shared, constant, texture, registers,...",
    "category": "cuda",
    "references": 5
  },
  {
    "name": "drizzle-orm",
    "title": "Drizzle Orm",
    "description": "Drizzle ORM for TypeScript/PostgreSQL: type-safe schema definition, queries, migrations, and Neon serverless integration. Use when writing, reviewing, or refactoring code with Drizzle ORM: (1)...",
    "category": "frontend",
    "references": 5
  },
  {
    "name": "fumadocs",
    "title": "Fumadocs",
    "description": "Fumadocs documentation framework for Next.js - project setup, content sources, MDX, layouts, UI components, search, OpenAPI, and i18n. Use when building documentation sites with Fumadocs, setting up...",
    "category": "frontend",
    "references": 7
  },
  {
    "name": "go-best-practices",
    "title": "Go Best Practices",
    "description": "Go (Golang) best practices, idioms, and modern patterns for writing clean, performant, and maintainable Go code. Covers error handling (errors.Is, errors.As, error wrapping, sentinel errors, custom...",
    "category": "go",
    "references": 5
  },
  {
    "name": "lead-hunter",
    "title": "Lead Hunter",
    "description": "Automated lead generation + enrichment for AI agents. Find prospects, enrich with emails/socials/company data, score & prioritize. Your agent builds pipeline while you sleep.",
    "category": "tools",
    "references": 0
  },
  {
    "name": "mcp-server-dev",
    "title": "Mcp Server Dev",
    "description": "Build MCP (Model Context Protocol) servers in TypeScript with @modelcontextprotocol/sdk. Use when writing, reviewing, or refactoring MCP server code: (1) Creating MCP servers with McpServer, (2)...",
    "category": "tools",
    "references": 4
  },
  {
    "name": "moebius-post-processing",
    "title": "Moebius Post Processing",
    "description": "Moebius-style (Jean Giraud) NPR post-processing shaders for React Three Fiber and Three.js. Hand-drawn outlines via Sobel filter on depth/normal buffers, crosshatched/tonal/raster shadow patterns,...",
    "category": "shaders",
    "references": 2
  },
  {
    "name": "neon-best-practices",
    "title": "Neon Best Practices",
    "description": "Neon serverless Postgres best practices for Next.js App Router: setup, connection pooling, branching, autoscaling, and authentication. Use when writing, reviewing, or refactoring Next.js code with...",
    "category": "frontend",
    "references": 4
  },
  {
    "name": "next-best-practices",
    "title": "Next Best Practices",
    "description": "Next.js best practices for the App Router (v14/v15/v16+). Use when writing, reviewing, or refactoring Next.js code: (1) File conventions - page, layout, loading, error, not-found, route, template,...",
    "category": "frontend",
    "references": 19
  },
  {
    "name": "painterly-kuwahara-shader",
    "title": "Painterly Kuwahara Shader",
    "description": "Painterly post-processing shaders using the Kuwahara filter for React Three Fiber, Three.js, and WebGL. Transforms 3D scenes into painting-like artwork (watercolor, gouache, oil paint, aquarelle) via...",
    "category": "shaders",
    "references": 3
  },
  {
    "name": "post-processing-shaders",
    "title": "Post Processing Shaders",
    "description": "Creative post-processing shader effects for React Three Fiber and Three.js using GLSL and the pmndrs/postprocessing library. Covers pixelation, cell patterns (receipt bars, halftone, ASCII, SDFs,...",
    "category": "shaders",
    "references": 3
  },
  {
    "name": "primeng",
    "title": "Primeng",
    "description": ">-",
    "category": "frontend",
    "references": 6
  },
  {
    "name": "python-best-practices",
    "title": "Python Best Practices",
    "description": "Idiomatic Python patterns, modern type hints, and best practices for writing clean, performant, and maintainable Python code (3.10+). Covers type annotations (generics, Protocol, TypeAlias,...",
    "category": "ai",
    "references": 5
  },
  {
    "name": "rag-pgvector",
    "title": "Rag Pgvector",
    "description": "RAG (Retrieval-Augmented Generation) pipelines with pgvector and PostgreSQL: vector storage, HNSW/IVFFlat indexes, hybrid search (dense + lexical), RRF fusion, chunking strategies, embedding...",
    "category": "ai",
    "references": 4
  },
  {
    "name": "ralph-tui-prd",
    "title": "Ralph Tui Prd",
    "description": "Generate a Product Requirements Document (PRD) for ralph-tui task orchestration. Creates PRDs with user stories that can be converted to beads issues or prd.json for automated execution. Triggers on:...",
    "category": "tools",
    "references": 0
  },
  {
    "name": "react-email-best-practices",
    "title": "React Email Best Practices",
    "description": "React Email framework for building and sending emails with React components, Tailwind CSS styling, and cross-client compatibility. Use when: (1) Creating email templates with React Email components...",
    "category": "frontend",
    "references": 3
  },
  {
    "name": "react-three-fiber",
    "title": "React Three Fiber",
    "description": ">-",
    "category": "shaders",
    "references": 5
  },
  {
    "name": "retro-dithering-crt",
    "title": "Retro Dithering Crt",
    "description": "Retro dithering, color quantization, and CRT post-processing shader effects for React Three Fiber and Three.js using GLSL and the pmndrs/postprocessing library. Implements ordered dithering (Bayer...",
    "category": "shaders",
    "references": 3
  },
  {
    "name": "rust-arc",
    "title": "Rust Arc",
    "description": "Rust Arc (Atomically Reference Counted) smart pointer for thread-safe shared ownership. Covers construction, cloning, mutation strategies (Mutex, RwLock, atomics, make_mut), Weak references for cycle...",
    "category": "rust",
    "references": 2
  },
  {
    "name": "rust-async",
    "title": "Rust Async",
    "description": "Rust async/await programming patterns, futures, streams, concurrency, and runtime usage. Covers async fn, .await syntax, Future trait, Poll, Pin/Unpin, join/try_join, select, spawn, async channels,...",
    "category": "rust",
    "references": 3
  },
  {
    "name": "rust-axum",
    "title": "Rust Axum",
    "description": "Axum 0.8 web framework for Rust: routing, extractors, handlers, middleware, responses, state, WebSockets, SSE, error handling, testing, Tower. Use when writing or reviewing Axum code: (1) Router and...",
    "category": "rust",
    "references": 6
  },
  {
    "name": "rust-best-practices",
    "title": "Rust Best Practices",
    "description": "Idiomatic Rust patterns, API design, and cross-cutting best practices for writing clean, performant, and maintainable Rust code. Covers newtype pattern, typestate pattern, builder pattern, RAII,...",
    "category": "rust",
    "references": 5
  },
  {
    "name": "rust-concurrency",
    "title": "Rust Concurrency",
    "description": "Rust concurrency and parallelism patterns: threads, message passing with channels, shared state with Mutex and Arc, Send and Sync marker traits, data races vs race conditions, and atomics with memory...",
    "category": "rust",
    "references": 3
  },
  {
    "name": "rust-crypto",
    "title": "Rust Crypto",
    "description": "Rust cryptography with RustCrypto crates: AES-GCM and ChaCha20Poly1305 authenticated encryption, HMAC message authentication, SHA-2 hashing, HKDF key derivation, Argon2 password hashing, Ed25519...",
    "category": "rust",
    "references": 8
  },
  {
    "name": "rust-ownership",
    "title": "Rust Ownership",
    "description": "Rust ownership, borrowing, and lifetime system from the Nomicon, Rust Book, and Rust Reference. Covers ownership rules, move semantics, Copy vs Clone, references, aliasing, reborrowing, NLL, lifetime...",
    "category": "rust",
    "references": 3
  },
  {
    "name": "rust-seaorm",
    "title": "Rust Seaorm",
    "description": "SeaORM async ORM for Rust (1.x stable + 2.0 RC): entity definition, CRUD operations, relations, migrations, transactions, and database patterns. Use when writing, reviewing, or refactoring Rust code...",
    "category": "rust",
    "references": 4
  },
  {
    "name": "rust-tokio",
    "title": "Rust Tokio",
    "description": "Tokio async runtime for Rust: task spawning, JoinSet, shared state, channels (mpsc/oneshot/broadcast/watch), sync primitives (Notify/Semaphore/Barrier/RwLock), timers (sleep/timeout/interval), async...",
    "category": "rust",
    "references": 6
  },
  {
    "name": "rust-traits",
    "title": "Rust Traits",
    "description": "Rust trait system best practices, patterns, and idiomatic usage. Covers trait definition, implementation, derive macros, dynamic dispatch (dyn), operator overloading (Add, Sub, Mul...), Drop,...",
    "category": "rust",
    "references": 5
  },
  {
    "name": "skill-creator",
    "title": "Skill Creator",
    "description": "Interactive guide for creating new skills (or updating existing skills) that extend Claude's capabilities with specialized knowledge, workflows, or tool integrations. Walks the user through use case...",
    "category": "tools",
    "references": 3
  },
  {
    "name": "tailwind-best-practices",
    "title": "Tailwind Best Practices",
    "description": ">-",
    "category": "frontend",
    "references": 9
  },
  {
    "name": "tanstack-form",
    "title": "Tanstack Form",
    "description": "TanStack Form v1.x for React: type-safe, performant, composable form management with validation, arrays, linked fields, listeners, and SSR support. Use when writing, reviewing, or refactoring React...",
    "category": "frontend",
    "references": 5
  },
  {
    "name": "tanstack-query",
    "title": "Tanstack Query",
    "description": "TanStack Query (React Query) v5 best practices for fetching, caching and updating server state in React. Use when: (1) Data fetching with useQuery, useSuspenseQuery, useInfiniteQuery, (2) Mutations...",
    "category": "frontend",
    "references": 4
  },
  {
    "name": "tanstack-store",
    "title": "Tanstack Store",
    "description": "TanStack Store framework-agnostic reactive state management with Store, Derived, Effect, and batch. Also powers TanStack Form's reactivity (form.store). Use when writing, reviewing, or refactoring...",
    "category": "frontend",
    "references": 2
  },
  {
    "name": "tanstack-table",
    "title": "Tanstack Table",
    "description": "TanStack Table v8 headless UI library for building type-safe tables and datagrids in React, Vue, Solid, Svelte, Qwik, Angular, and Lit. Use when writing, reviewing, or refactoring code involving...",
    "category": "frontend",
    "references": 4
  },
  {
    "name": "tsl-webgpu",
    "title": "Tsl Webgpu",
    "description": "TSL (Three.js Shading Language) and WebGPU shader development with Three.js. Write, review, and refactor GPU shaders using TSL's node system, compute shaders, and WebGPU renderer. Use when: (1)...",
    "category": "shaders",
    "references": 3
  },
  {
    "name": "volumetric-lighting",
    "title": "Volumetric Lighting",
    "description": "Real-time volumetric lighting with post-processing and raymarching for React Three Fiber and Three.js. Implements god rays, light beams, atmospheric fog, and shadow-casting volumetric effects as...",
    "category": "shaders",
    "references": 6
  },
  {
    "name": "web-3d-shaders",
    "title": "Web 3d Shaders",
    "description": ">-",
    "category": "shaders",
    "references": 7
  }
];

export const GITHUB_REPO = "https://github.com/ArthurDEV44/skills";
