// Auto-generated by scripts/sync-all.mjs — do not edit manually.
// Source: /home/arthur/dev/skills

export const GITHUB_REPO = "https://github.com/ArthurDEV44/skills";
export const GITHUB_RAW = "https://raw.githubusercontent.com/ArthurDEV44/skills/main";

export interface Workflow {
  name: string;
  title: string;
  description: string;
  agents: string[];
  files: string[];
}

export interface Subagent {
  name: string;
  description: string;
  model: string;
  tools: string[];
}

export const workflows: Workflow[] = [
  {
    "name": "build-saas",
    "title": "Build Saas",
    "description": "End-to-end SaaS creation workflow from idea to PRD. Researches via /meta-code, brainstorms with research-backed questions, validates the concept, defines architecture using the user's preferred tech...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/saas-brainstorm.md",
      "references/saas-prd-template.md",
      "references/stack-defaults.md"
    ]
  },
  {
    "name": "extract-catalog",
    "title": "Extract Catalog",
    "description": "Extract product metadata from any supplier catalog PDF and output structured JSON aligned with the project's hybrid DB schema (relational columns + JSONB attributes). Schema-driven: auto-discovers DB...",
    "agents": [],
    "files": [
      "SKILL.md",
      "references/catalog-profiles/k-emotion-tiles.md",
      "references/catalog-profiles/karag-bagno.md",
      "references/catalog-profiles/karag-box-doccia.md",
      "references/catalog-profiles/karag-furniture.md",
      "references/schema-contract.md",
      "references/value-mappings.md"
    ]
  },
  {
    "name": "frontend-design",
    "title": "Frontend Design",
    "description": "Create distinctive, production-grade frontend interfaces with the intentionality of a senior human web designer. Rejects generic AI aesthetics: no gratuitous animations, no neon glow, no purple...",
    "agents": [
      "agent-websearch"
    ],
    "files": [
      "SKILL.md",
      "references/animation-policy.md",
      "references/anti-patterns.md",
      "references/color-system.md",
      "references/component-distinctiveness.md",
      "references/design-philosophy.md",
      "references/industry-archetypes.md",
      "references/layout-patterns.md",
      "references/question-templates.md",
      "references/research-methodology.md",
      "references/texture-and-depth.md",
      "references/typography.md"
    ]
  },
  {
    "name": "implement-story",
    "title": "Implement Story",
    "description": "End-to-end workflow to implement a user story from a PRD. Orchestrates 9 phases: intake, research (/meta-code pipeline), planning, implementation, static analysis, code review, security audit,...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/phase-protocols.md"
    ]
  },
  {
    "name": "meta-code",
    "title": "Meta Code",
    "description": "Intelligent multi-agent workflow that answers development questions by orchestrating web research, codebase exploration, and documentation lookup in an adaptive pipeline with quality gates,...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/agent-protocols.md",
      "references/research-notes.md",
      "references/workflow-engine.md"
    ]
  },
  {
    "name": "meta-debug",
    "title": "Meta Debug",
    "description": "Multi-agent debugging workflow that diagnoses and fixes errors with surgical precision. Orchestrates agent-explore (root cause), agent-docs (API verification), and agent-websearch (community...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/agent-orchestration.md",
      "references/error-patterns.md",
      "references/fix-strategies.md",
      "references/research-sources.md"
    ]
  },
  {
    "name": "meta-prompt",
    "title": "Meta Prompt",
    "description": "Generate ultra-optimized prompts for Claude Code to build apps, SaaS, ecommerce, and any software project. Use when the user says \"meta prompt\", \"generate a prompt\", \"optimize this prompt\", \"create a...",
    "agents": [],
    "files": [
      "SKILL.md",
      "references/techniques.md",
      "references/templates.md"
    ]
  },
  {
    "name": "prospect-analyzer",
    "title": "Prospect Analyzer",
    "description": "Pipeline d'analyse de prospect et génération de messages LinkedIn sur-mesure. Extrait les données des URLs (LinkedIn profil, LinkedIn entreprise, site web), analyse le prospect contre l'ICP StriveX,...",
    "agents": [
      "agent-websearch"
    ],
    "files": [
      "SKILL.md",
      "references/extraction-schema.md",
      "references/message-rules.md"
    ]
  },
  {
    "name": "react-doctor",
    "title": "React Doctor",
    "description": "React codebase health scanner that checks for security, performance, correctness, and architecture issues. Runs react-doctor CLI, interprets results, and provides actionable fix guidance. Use when...",
    "agents": [],
    "files": [
      "SKILL.md"
    ]
  },
  {
    "name": "refactor",
    "title": "Refactor",
    "description": "Multi-agent refactoring workflow that analyzes, plans, executes, simplifies, and validates code improvements across files or entire directories. Optimizes performance, cleans legacy code, enforces...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/agent-orchestration.md",
      "references/analysis-checklist.md",
      "references/optimization-patterns.md"
    ]
  },
  {
    "name": "review-story",
    "title": "Review Story",
    "description": "End-to-end review and correction workflow for an implemented user story or a complete PRD. Orchestrates 7 phases: intake, research (/meta-code pipeline), static analysis, parallel AI code review +...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/review-protocols.md"
    ]
  },
  {
    "name": "saas-storytelling",
    "title": "Saas Storytelling",
    "description": "Storytelling et copywriting pour tout SaaS GenAI. Genere du contenu structure par type : landing-page, blog, article, dashboard-ui, changelog, feature-announcement. Part du probleme utilisateur, cree...",
    "agents": [
      "agent-websearch",
      "agent-explore"
    ],
    "files": [
      "SKILL.md",
      "references/conversion-patterns.md",
      "references/landing-page-anatomy.md",
      "references/narrative-frameworks.md",
      "references/voice-tone.md"
    ]
  },
  {
    "name": "security-review",
    "title": "Security Review",
    "description": "Comprehensive security audit of code changes. Analyzes changed files for OWASP Top 10 vulnerabilities, injection flaws, authentication issues, secrets exposure, and insecure patterns. Produces a...",
    "agents": [],
    "files": [
      "SKILL.md",
      "references/security-checklist.md"
    ]
  },
  {
    "name": "seo-warfare",
    "title": "Seo Warfare",
    "description": "SEO audit, optimization, and generation pipeline for traditional search and AI search (Google AI Overviews, ChatGPT Search, Perplexity). Orchestrates agent-websearch, agent-explore, and agent-docs in...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/ai-search-optimization.md",
      "references/competitive-analysis.md",
      "references/content-strategy.md",
      "references/core-web-vitals.md",
      "references/meta-tags-templates.md",
      "references/structured-data.md",
      "references/technical-seo.md"
    ]
  },
  {
    "name": "write-prd",
    "title": "Write Prd",
    "description": "Research-informed PRD generator with epics, user stories, and status tracking. Researches the domain via /meta-code pipeline before brainstorming, then asks research-backed questions grounded in real...",
    "agents": [
      "agent-websearch",
      "agent-explore",
      "agent-docs"
    ],
    "files": [
      "SKILL.md",
      "references/brainstorm-protocols.md",
      "references/prd-template.md"
    ]
  }
];

export const subagents: Subagent[] = [
  {
    "name": "agent-docs",
    "description": "Ultra-specialized documentation lookup agent powered by Context7 MCP. Resolves library IDs, queries up-to-date documentation and code examples for any programming library or framework. Combines...",
    "model": "sonnet",
    "tools": [
      "Read",
      "Grep",
      "Glob",
      "mcp__context7__resolve-library-id",
      "mcp__context7__query-docs",
      "mcp__plugin_context7_context7__resolve-library-id",
      "mcp__plugin_context7_context7__query-docs"
    ]
  },
  {
    "name": "agent-explore",
    "description": "Elite codebase exploration and analysis agent. Systematically maps architecture, traces execution flows, analyzes patterns, and builds deep understanding of any codebase — from micro-libraries to...",
    "model": "sonnet",
    "tools": [
      "Read",
      "Grep",
      "Glob",
      "Bash"
    ]
  },
  {
    "name": "agent-websearch",
    "description": "Expert web research agent. Uses Exa MCP tools (primary) with native WebSearch/WebFetch fallback. Read-only — never modifies files, only returns research findings.",
    "model": "sonnet",
    "tools": [
      "WebSearch",
      "WebFetch",
      "Read",
      "Grep",
      "Glob",
      "mcp__exa__web_search_exa",
      "mcp__exa__company_research_exa",
      "mcp__exa__get_code_context_exa"
    ]
  }
];
